feat: add new components: PrimaryButton, SvgSpriteIcon
baza-trainee/kavaleridze pull request #7
Opened 2023-08-18 11:35 UTC by YevhenOnufrii

2023-08-19 09:47 UTC, volodimirzhukivskyi requested changes

2023-08-19 09:47 UTC, volodimirzhukivskyi commented on src/components/PrimaryButton/PrimaryButton.tsx
> +    <Box>
а навіщо над кнопкою створювати div?

2023-08-19 09:47 UTC, volodimirzhukivskyi commented on src/components/PrimaryButton/SvgSpriteIcon.tsx
> +      <use href={`/sprite.svg#${svgSpriteId}`}></use>
Є питання sprite буде один чи їх буде декілька від цього залежить правильність href

2023-08-19 11:14 UTC, YevhenOnufrii commented on src/components/PrimaryButton/PrimaryButton.tsx
> +    <Box>
для того щоб зовнішні стилі не перебивали стилі самої кнопки. Наприклад, якщо кнопка стане флекс елементом, то  її розтягне на всю ширину батьківського елемента. Додатковий контейнер вбереже її від такої поведінки

2023-08-20 07:55 UTC, AndriiBohonis approved these changes

2023-08-20 07:56 UTC, merged